### ISSUE TITLE
股票因子如何计算或者具体什么含义

### ISSUE THREAD

**Issue by wangsheng1991** [frinkleko/FinReport#4]
![image](https://github.com/frinkleko/FinReport/assets/3817565/54373fab-5556-44d4-a3a0-4085da05cd00)
你好，我看到你的代码里面用到这些因子，但是在网络上没有找到具体的定义符合这些数据的取值范围，能提供进一步的相关资料吗，非常感谢

**Comment by frinkleko** [comment]
您好，这些都是比较常见的因子（如’Abnormal Turnover') ，应当可以在网络上获取到参考来源。此处为您提供可以进一步参考的[资料](https://github.com/jealous/stockstats)。本repo中提供的因子数据爬取自东方财富Choice平台API，确保了赋权数据一定。您可以在该平台API文档中找到同名因子。
