### ISSUE TITLE
数据问题 

### ISSUE THREAD

**Issue by wangsheng1991** [frinkleko/FinReport#5]
我看到很多标签为2的实际上是涨停的数据 这个对于实际交易没什么用吧  能否解释一下

**Comment by wangsheng1991** [comment]
高度怀疑是不是把数据洗过 这个数据严重失真  这个竟然还可以发顶会 😄

**Comment by frinkleko** [comment]
对于标签的设置，我们follow [Astock数据集论文](https://aclanthology.org/2022.finnlp-1.24)中Section 3.2.1的要求，并直接使用该数据集。
![image](https://github.com/frinkleko/FinReport/assets/32212221/56d7db16-5cfc-4e24-a055-63624ec4e73f)
为了避免进一步的歧义，此处提供工作初期我们与Astock数据集作者对于标签定义的确认。
![image](https://github.com/frinkleko/FinReport/assets/32212221/d33a15c4-333b-4008-94c7-0a712bf80bab)
![image](https://github.com/frinkleko/FinReport/assets/32212221/2ed97276-4aec-42c7-9565-37885ddd4bbb)
根据此处提到的定义，涨停股被标注为2是正常的。
更多信息可以在[此处](https://github.com/JinanZou/Astock)找到Astock数据集的repo。
